import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });

const euclid = localfont({
  src: [
    {
      path: "../../public/fonts/EuclidCircularARegular.ttf",
      weight: "700",
    },
  ],
  variable: "--font-euclid",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${euclid.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
