import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";
import { useMediaQuery } from "react-responsive";
import DesktopHeader from "./(components)/DesktopHeader";
import MobileSidebar from "./(components)/MobileSidebar";
import Providers from "./(components)/Providers";
const inter = Inter({ subsets: ["latin"] });

const euclid = localfont({
  src: [
    {
      path: "../../public/fonts/EuclidFlexRegular.ttf",
      weight: "700",
    },
  ],
  variable: "--font-euclid",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDesktopOrLaptop = useMediaQuery({
    query: "(min-width: 1000px)",
  });
  return (
    <html lang="en" className={`${euclid.variable} font-sans`}>
      <body>
        <Providers>
          {isDesktopOrLaptop ? <DesktopHeader /> : <MobileSidebar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
